# Site
name: 'BestHostingDeals'
description: '"Unlock Affordable Hosting Excellence with BestHostingDeals.'
logo: 'assets/images/favicon-32x32.png'
favicon: 'assets/images/bestico.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'michael.honey18@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
author:
    BestHostingDeals:
      name:           BestHostingDeals
      site:           https://BestHostingDeals.online
      avatar:         /assets/images/WEBHOSTDP.jpg
      bio:            "Your gateway to unbeatable hosting deals! Discover top-notch web hosting solutions and exclusive offers. Empowering your online presence, one deal at a time."
      email:          michael.honey18@gmail.com
      facebook:        https://www.facebook.com/besthostingdealsonline

   
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: BestHostingDeals
      avatar: /assets/images/WEBHOSTDP.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
