# Site
name: 'BestHostingDeals'
description: '"Unlock Affordable Hosting Excellence with BestHostingDeals.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'michael.honey18@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    BestHostingDeals:
      name:           BestHostingDeals
      site:           https://BestHostingDeals.online
      avatar:         /assets/images/WEBHOSTDP.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          michael.honey18@gmail.com
      facebook:        https://www.facebook.com/besthostingdealsonline

   
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: BestHostingDeals
      avatar: /assets/images/WEBHOSTDP.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
